### ISSUE TITLE
Breaking with July release of React Native?

### ISSUE THREAD

**Issue by phsumi** [emin93/react-native-template-typescript#18]
FYI, this seems to be breaking with the latest CLI 6.1.0:

```
D:\MyProject\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Module._compile (D:\MyProject\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:646:10)
    at Object.newLoader [as .js] (D:\MyProject\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

```

**Comment by phsumi** [comment]
Ha, I stand corrected! Turns out the CLI also crashes without your template, so it's either my system, or the RN script itself has an issue. Sorry for bothering you!

**Comment by emin93** [comment]
Hi @phsumi,

Thanks for reporting the issue. I tried to reproduce it on my local machine, but for me everything worked just fine. It seems you're on a Windows machine, maybe it's a Windows related issue?

Have you checked the React Native issues?

**Comment by phsumi** [comment]
Yes, it's an RN issue. It appear 0.56 is broken on Windows - no idea why they released it in the first place. Sorry for the confusion!

**Comment by emin93** [comment]
No worries, I'm glad you found the issue. Hopefully they'll fix it soon.
